package com.lczy.media.entity;

// Generated 2015-3-27 18:53:05 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Area generated by hbm2java
 */
@Entity
@Table(name = "c_area")
public class Area implements java.io.Serializable {

	private static final long serialVersionUID = 7113871410750493848L;
	private String id;
	private String name;
	private String english;
	private String level;
	private String parentId;
	private String areaCode;
	private String zipCode;
	private boolean hot;
	private String regionName;
	private int seqNum;

	public Area() {
	}
	
	public Area(String id, String name, String level, String parentId,
			int seqNum) {
		this.id = id;
		this.name = name;
		this.level = level;
		this.parentId = parentId;
		this.seqNum = seqNum;
	}



	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "NAME", nullable = false, length = 32)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "ENGLISH", length = 100)
	public String getEnglish() {
		return this.english;
	}

	public void setEnglish(String english) {
		this.english = english;
	}

	@Column(name = "LEVEL", nullable = false, length = 32)
	public String getLevel() {
		return this.level;
	}

	public void setLevel(String level) {
		this.level = level;
	}

	@Column(name = "PARENT_ID", length = 32)
	public String getParentId() {
		return this.parentId;
	}

	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	@Column(name = "AREA_CODE", length = 32)
	public String getAreaCode() {
		return this.areaCode;
	}

	public void setAreaCode(String areaCode) {
		this.areaCode = areaCode;
	}

	@Column(name = "ZIP_CODE", length = 32)
	public String getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	@Column(name = "SEQ_NUM", precision = 3, scale = 0)
	public int getSeqNum() {
		return this.seqNum;
	}

	public void setSeqNum(int seqNum) {
		this.seqNum = seqNum;
	}

	@Column(name = "HOT")
	public boolean isHot() {
		return hot;
	}

	public void setHot(boolean hot) {
		this.hot = hot;
	}

	@Column(name = "REGION_NAME")
	public String getRegionName() {
		return regionName;
	}

	public void setRegionName(String regionName) {
		this.regionName = regionName;
	}

	
}
