package com.lczy.media.entity;

// Generated 2015-6-30 13:49:25 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * Complaint generated by hbm2java
 */
@Entity
@Table(name = "t_complaint")
public class Complaint implements java.io.Serializable {

	private static final long serialVersionUID = 4877869350349531155L;
	
	private String id;
	private Order order;
	private String type;
	private String reason;
	private String createBy;
	private Date createTime;
	private String handler;
	private Date handleTime;
	private String handleResult;
	private String handleComment;

	public Complaint() {
	}

	public Complaint(String id, Order order, String type, String reason,
			Date createTime) {
		this.id = id;
		this.order = order;
		this.type = type;
		this.reason = reason;
		this.createTime = createTime;
	}

	public Complaint(String id, Order order, String type, String reason,
			Date createTime, String handler, Date handleTime,
			String handleResult, String handleComment, Set<Order> orders) {
		this.id = id;
		this.order = order;
		this.type = type;
		this.reason = reason;
		this.createTime = createTime;
		this.handler = handler;
		this.handleTime = handleTime;
		this.handleResult = handleResult;
		this.handleComment = handleComment;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@GeneratedValue(generator = "system-uuid")
	@GenericGenerator(name = "system-uuid", strategy = "uuid")
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ORDER_ID", nullable = false)
	public Order getOrder() {
		return this.order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

	@Column(name = "TYPE", nullable = false, length = 32)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "REASON", nullable = false, length = 1500)
	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}
	
	@Column(name = "CREATE_BY", length = 32)
	public String getCreateBy() {
		return createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", nullable = false, length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "HANDLER", length = 32)
	public String getHandler() {
		return this.handler;
	}

	public void setHandler(String handler) {
		this.handler = handler;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "HANDLE_TIME", length = 19)
	public Date getHandleTime() {
		return this.handleTime;
	}

	public void setHandleTime(Date handleTime) {
		this.handleTime = handleTime;
	}

	@Column(name = "HANDLE_RESULT", length = 32)
	public String getHandleResult() {
		return this.handleResult;
	}

	public void setHandleResult(String handleResult) {
		this.handleResult = handleResult;
	}

	@Column(name = "HANDLE_COMMENT", length = 1500)
	public String getHandleComment() {
		return this.handleComment;
	}

	public void setHandleComment(String handleComment) {
		this.handleComment = handleComment;
	}

}
