package com.lczy.media.entity;

// Generated 2015-3-27 17:06:05 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Customer generated by hbm2java
 */
/**
 * @author wu
 *
 */
@Entity
@Table(name = "t_customer")
@Cache(usage=CacheConcurrencyStrategy.READ_WRITE)
public class Customer implements java.io.Serializable {

	private static final long serialVersionUID = -4108353141362004383L;
	
	private String id;
	private CustLevel custLevel;
	private String name;
	private String custType;
	private String custProperty;
	private String telPhone;
	private String mobPhone;
	private Integer credit;
	private String linkman;
	private String email;
	private String qq;
	private String createBy;
	private Date createTime;
	private String modifyBy;
	private Date modifyTime;
	private String status;
	private Set<CustCreditLog> creditLogs = new HashSet<CustCreditLog>(0);
	private Set<CustLevelLog> levelLogs = new HashSet<CustLevelLog>(0);
	private Set<Article> articles = new HashSet<Article>(0);
	private Set<User> users = new HashSet<User>(0);
	private Set<Media> medias = new HashSet<Media>(0);
	private Set<Requirement> requirements = new HashSet<Requirement>(0);
	private Account account;

	private boolean certified;
	private String certStatus;
	private String certName;
	private String certIdentity;
	private String certMatter;
	private Date certSubmitTime;
	
	private String orgType;
	private String orgSummary;
	
	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@GenericGenerator( name="id_gen", strategy="com.lczy.common.data.FormatTableGenerator", 
	   parameters = {
			@Parameter( name = "format",         value = "%1$ty%1$tm%1$td%2$06d"),
			@Parameter( name = "table_name",     value = "sys_sequences"),
			@Parameter( name = "segment_value",  value = "cust_seq"),
			@Parameter( name = "increment_size", value = "10"), 
			@Parameter( name = "optimizer",      value = "pooled-lo")
	   })
	@GeneratedValue(generator="id_gen")
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CUST_LEVEL")
	public CustLevel getCustLevel() {
		return this.custLevel;
	}

	public void setCustLevel(CustLevel custLevel) {
		this.custLevel = custLevel;
	}

	@Column(name = "NAME", nullable = false, length = 64)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "CUST_TYPE", nullable = false, length = 32)
	public String getCustType() {
		return this.custType;
	}

	public void setCustType(String custType) {
		this.custType = custType;
	}

	@Column(name = "CUST_PROPERTY", length = 32)
	public String getCustProperty() {
		return this.custProperty;
	}

	public void setCustProperty(String custProperty) {
		this.custProperty = custProperty;
	}

	@Column(name = "TEL_PHONE", length = 20)
	public String getTelPhone() {
		return this.telPhone;
	}

	public void setTelPhone(String telPhone) {
		this.telPhone = telPhone;
	}

	@Column(name = "MOB_PHONE", nullable = false, length = 20)
	public String getMobPhone() {
		return this.mobPhone;
	}

	public void setMobPhone(String mobPhone) {
		this.mobPhone = mobPhone;
	}

	@Column(name = "CREDIT")
	public Integer getCredit() {
		return this.credit;
	}

	public void setCredit(Integer credit) {
		this.credit = credit;
	}

	@Column(name = "CREATE_BY", length = 32)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", nullable = false, length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "MODIFY_BY", length = 32)
	public String getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_TIME", nullable = false, length = 19)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	@Column(name = "STATUS", nullable = false, length = 32)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<CustCreditLog> getCreditLogs() {
		return this.creditLogs;
	}

	public void setCreditLogs(Set<CustCreditLog> creditLogs) {
		this.creditLogs = creditLogs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<CustLevelLog> getLevelLogs() {
		return this.levelLogs;
	}

	public void setLevelLogs(Set<CustLevelLog> levelLogs) {
		this.levelLogs = levelLogs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<Article> getArticles() {
		return this.articles;
	}

	public void setArticles(Set<Article> articles) {
		this.articles = articles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<Media> getMedias() {
		return this.medias;
	}

	public void setMedias(Set<Media> medias) {
		this.medias = medias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<Requirement> getRequirements() {
		return this.requirements;
	}

	public void setRequirements(Set<Requirement> requirements) {
		this.requirements = requirements;
	}

	@OneToOne(fetch=FetchType.LAZY, cascade={CascadeType.PERSIST, CascadeType.REMOVE})
	@JoinColumn(name = "ACCOUNT_ID")
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@Column(name = "LINKMAN", nullable = true)
	public String getLinkman() {
		return linkman;
	}

	public void setLinkman(String linkman) {
		this.linkman = linkman;
	}

	@Column(name = "EMAIL", nullable = true)
	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "QQ", nullable = true)
	public String getQq() {
		return qq;
	}

	public void setQq(String qq) {
		this.qq = qq;
	}
	
	@Column(name = "CERTIFIED")
	public boolean isCertified() {
		return certified;
	}

	public void setCertified(boolean certified) {
		this.certified = certified;
	}

	@Column(name = "CERT_STATUS")
	public String getCertStatus() {
		return certStatus;
	}

	public void setCertStatus(String certStatus) {
		this.certStatus = certStatus;
	}

	@Column(name = "CERT_NAME")
	public String getCertName() {
		return certName;
	}

	public void setCertName(String certName) {
		this.certName = certName;
	}

	@Column(name = "CERT_IDENTITY")
	public String getCertIdentity() {
		return certIdentity;
	}

	public void setCertIdentity(String certIdentity) {
		this.certIdentity = certIdentity;
	}

	@Column(name = "CERT_MATTER")
	public String getCertMatter() {
		return certMatter;
	}

	public void setCertMatter(String certMatter) {
		this.certMatter = certMatter;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CERT_SUBMIT_TIME")
	public Date getCertSubmitTime() {
		return certSubmitTime;
	}

	public void setCertSubmitTime(Date certSubmitTime) {
		this.certSubmitTime = certSubmitTime;
	}

	@Column(name = "ORG_TYPE")
	public String getOrgType() {
		return orgType;
	}

	public void setOrgType(String orgType) {
		this.orgType = orgType;
	}

	@Column(name = "ORG_SUMMARY")
	public String getOrgSummary() {
		return orgSummary;
	}

	public void setOrgSummary(String orgSummary) {
		this.orgSummary = orgSummary;
	}
	
}
