package com.lczy.media.entity;

// Generated 2015-6-30 13:49:25 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.hibernate.annotations.GenericGenerator;

/**
 * CustLevel generated by hbm2java
 */
@Entity
@Table(name = "t_cust_level")
@Cache(usage=CacheConcurrencyStrategy.READ_ONLY)
public class CustLevel implements java.io.Serializable {

	private static final long serialVersionUID = 2715123261766034570L;
	
	private String id;
	private CustLevel nextLevel;
	private String name;
	private int credit;
	private String noAudit;
	private String discount;
	private String redName;
	private String priority;
	private int reward;
	private Set<Customer> customers = new HashSet<Customer>(0);

	public CustLevel() {
	}

	public CustLevel(String id, String name, int credit, String noAudit,
			String discount, String redName, String priority, int reward) {
		this.id = id;
		this.name = name;
		this.credit = credit;
		this.noAudit = noAudit;
		this.discount = discount;
		this.redName = redName;
		this.priority = priority;
		this.reward = reward;
	}

	public CustLevel(String id, CustLevel custLevel, String name, int credit,
			String noAudit, String discount, String redName, String priority,
			int reward, Set<CustLevel> custLevels, Set<Customer> customers) {
		this.id = id;
		this.nextLevel = custLevel;
		this.name = name;
		this.credit = credit;
		this.noAudit = noAudit;
		this.discount = discount;
		this.redName = redName;
		this.priority = priority;
		this.reward = reward;
		this.customers = customers;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@GeneratedValue(generator = "system-uuid")
	@GenericGenerator(name = "system-uuid", strategy = "uuid")
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NEXT_ID")
	public CustLevel getNextLevel() {
		return this.nextLevel;
	}

	public void setNextLevel(CustLevel nextLevel) {
		this.nextLevel = nextLevel;
	}

	@Column(name = "NAME", nullable = false, length = 32)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "CREDIT", nullable = false)
	public int getCredit() {
		return this.credit;
	}

	public void setCredit(int credit) {
		this.credit = credit;
	}

	@Column(name = "NO_AUDIT", nullable = false, length = 1)
	public String getNoAudit() {
		return this.noAudit;
	}

	public void setNoAudit(String noAudit) {
		this.noAudit = noAudit;
	}

	@Column(name = "DISCOUNT", nullable = false, length = 1)
	public String getDiscount() {
		return this.discount;
	}

	public void setDiscount(String discount) {
		this.discount = discount;
	}

	@Column(name = "RED_NAME", nullable = false, length = 1)
	public String getRedName() {
		return this.redName;
	}

	public void setRedName(String redName) {
		this.redName = redName;
	}

	@Column(name = "PRIORITY", nullable = false, length = 1)
	public String getPriority() {
		return this.priority;
	}

	public void setPriority(String priority) {
		this.priority = priority;
	}

	@Column(name = "REWARD", nullable = false)
	public int getReward() {
		return this.reward;
	}

	public void setReward(int reward) {
		this.reward = reward;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "custLevel")
	public Set<Customer> getCustomers() {
		return this.customers;
	}

	public void setCustomers(Set<Customer> customers) {
		this.customers = customers;
	}

}
