package com.lczy.media.entity;

// Generated 2015-3-27 18:53:05 by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Cacheable;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Dic generated by hbm2java
 */
@Entity
@Table(name = "c_dic")
@Cacheable
public class Dic {

	private String id;
	private String dicCode;
	private String dicName;
	private String parentId;
	private Long seqNum;
	private List<DicItem> dicItems = new ArrayList<DicItem>(0);

	public Dic() {
	}

	public Dic(String id, String dicCode, String dicName) {
		this.id = id;
		this.dicCode = dicCode;
		this.dicName = dicName;
	}


	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@GeneratedValue(generator = "system-uuid")
	@GenericGenerator(name = "system-uuid", strategy = "uuid")
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "DIC_CODE", nullable = false, length = 20)
	public String getDicCode() {
		return this.dicCode;
	}

	public void setDicCode(String dicCode) {
		this.dicCode = dicCode;
	}

	@Column(name = "DIC_NAME", nullable = false, length = 128)
	public String getDicName() {
		return this.dicName;
	}

	public void setDicName(String dicName) {
		this.dicName = dicName;
	}

	@Column(name = "PARENT_ID", length = 32)
	public String getParentId() {
		return this.parentId;
	}

	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	@Column(name = "SEQ_NUM", precision = 10, scale = 0)
	public Long getSeqNum() {
		return this.seqNum;
	}

	public void setSeqNum(Long seqNum) {
		this.seqNum = seqNum;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dic", cascade = CascadeType.ALL)
	@OrderBy("seqNum")
	public List<DicItem> getDicItems() {
		return this.dicItems;
	}

	public void setDicItems(List<DicItem> dicItems) {
		this.dicItems = dicItems;
	}

}
