package com.lczy.media.entity;

// Generated 2015-3-27 17:06:05 by Hibernate Tools 4.3.1

import javax.persistence.Cacheable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Media generated by hbm2java
 */
@Entity
@Table(name = "t_media_input")
@Cacheable
public class MediaInput {

	private String id;
	private String mobPhone;
	private String password;
	private String name;
	private String account;
	private String description;
	private String showPic;
	private String mediaType;
	private String category;
	private String industryType;
	private String region;
	private String products;
	private Integer fans;
	private String fansDir;
	
	private String caseTitle;
	private String caseLight;
	private String caseContent;
	private String caseTitle1;
	private String caseLight1;
	private String caseContent1;

	private String quoteType;
	private Integer quotePrice;
	private String quoteType1;
	private Integer quotePrice1;
	private String quoteType2;
	private Integer quotePrice2;
	private String quoteType3;
	private Integer quotePrice3;
	private String quoteType4;
	private Integer quotePrice4;
	
	public MediaInput() {
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@GeneratedValue(generator = "system-uuid")
	@GenericGenerator(name = "system-uuid", strategy = "uuid")
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "NAME", nullable = false, length = 64)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "ACCOUNT", nullable = false, length = 64)
	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	@Column(name = "DESCRIPTION", nullable = false, length = 3000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "SHOW_PIC", length = 256)
	public String getShowPic() {
		return this.showPic;
	}

	public void setShowPic(String showPic) {
		this.showPic = showPic;
	}

	@Column(name = "MEDIA_TYPE", length = 32)
	public String getMediaType() {
		return this.mediaType;
	}

	public void setMediaType(String mediaType) {
		this.mediaType = mediaType;
	}

	@Column(name = "CATEGORY", length = 32)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "INDUSTRY_TYPE", length = 32)
	public String getIndustryType() {
		return this.industryType;
	}

	public void setIndustryType(String industryType) {
		this.industryType = industryType;
	}

	@Column(name = "REGION", nullable = false, length = 32)
	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	@Column(name = "PRODUCTS", length = 300)
	public String getProducts() {
		return this.products;
	}

	public void setProducts(String products) {
		this.products = products;
	}

	@Column(name = "FANS")
	public Integer getFans() {
		return this.fans;
	}

	public void setFans(Integer fans) {
		this.fans = fans;
	}

	@Column(name = "FANS_DIR", length = 32)
	public String getFansDir() {
		return this.fansDir;
	}

	public void setFansDir(String fansDir) {
		this.fansDir = fansDir;
	}

	@Column(name = "MOB_PHONE", length = 32)
	public String getMobPhone() {
		return mobPhone;
	}

	public void setMobPhone(String mobPhone) {
		this.mobPhone = mobPhone;
	}

	@Column(name = "PASSWORD", length = 32)
	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "CASE_TITLE", length = 150)
	public String getCaseTitle() {
		return caseTitle;
	}

	public void setCaseTitle(String caseTitle) {
		this.caseTitle = caseTitle;
	}

	@Column(name = "CASE_LIGHT", length = 150)
	public String getCaseLight() {
		return caseLight;
	}

	public void setCaseLight(String caseLight) {
		this.caseLight = caseLight;
	}

	@Column(name = "CASE_CONTENT", length = 5000)
	public String getCaseContent() {
		return caseContent;
	}

	public void setCaseContent(String caseContent) {
		this.caseContent = caseContent;
	}

	@Column(name = "CASE_TITLE1", length = 150)
	public String getCaseTitle1() {
		return caseTitle1;
	}

	public void setCaseTitle1(String caseTitle1) {
		this.caseTitle1 = caseTitle1;
	}

	@Column(name = "CASE_LIGHT1", length = 150)
	public String getCaseLight1() {
		return caseLight1;
	}

	public void setCaseLight1(String caseLight1) {
		this.caseLight1 = caseLight1;
	}

	@Column(name = "CASE_CONTENT1", length = 5000)
	public String getCaseContent1() {
		return caseContent1;
	}

	public void setCaseContent1(String caseContent1) {
		this.caseContent1 = caseContent1;
	}

	@Column(name = "QUOTE_TYPE", length = 32)
	public String getQuoteType() {
		return quoteType;
	}

	public void setQuoteType(String quoteType) {
		this.quoteType = quoteType;
	}

	@Column(name = "QUOTE_PRICE")
	public Integer getQuotePrice() {
		return quotePrice;
	}

	public void setQuotePrice(Integer quotePrice) {
		this.quotePrice = quotePrice;
	}

	@Column(name = "QUOTE_TYPE1", length = 32)
	public String getQuoteType1() {
		return quoteType1;
	}

	public void setQuoteType1(String quoteType1) {
		this.quoteType1 = quoteType1;
	}

	@Column(name = "QUOTE_PRICE1")
	public Integer getQuotePrice1() {
		return quotePrice1;
	}

	public void setQuotePrice1(Integer quotePrice1) {
		this.quotePrice1 = quotePrice1;
	}

	@Column(name = "QUOTE_TYPE2", length = 32)
	public String getQuoteType2() {
		return quoteType2;
	}

	public void setQuoteType2(String quoteType2) {
		this.quoteType2 = quoteType2;
	}

	@Column(name = "QUOTE_PRICE2")
	public Integer getQuotePrice2() {
		return quotePrice2;
	}

	public void setQuotePrice2(Integer quotePrice2) {
		this.quotePrice2 = quotePrice2;
	}

	@Column(name = "QUOTE_TYPE3", length = 32)
	public String getQuoteType3() {
		return quoteType3;
	}

	public void setQuoteType3(String quoteType3) {
		this.quoteType3 = quoteType3;
	}

	@Column(name = "QUOTE_PRICE3")
	public Integer getQuotePrice3() {
		return quotePrice3;
	}

	public void setQuotePrice3(Integer quotePrice3) {
		this.quotePrice3 = quotePrice3;
	}

	@Column(name = "QUOTE_TYPE4", length = 32)
	public String getQuoteType4() {
		return quoteType4;
	}

	public void setQuoteType4(String quoteType4) {
		this.quoteType4 = quoteType4;
	}

	@Column(name = "QUOTE_PRICE4")
	public Integer getQuotePrice4() {
		return quotePrice4;
	}

	public void setQuotePrice4(Integer quotePrice4) {
		this.quotePrice4 = quotePrice4;
	}

}
