package com.lczy.media.entity;

// Generated 2015-3-31 12:34:17 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * MediaWeixin generated by hbm2java
 */
@Entity
@Table(name = "t_media_weixin")
@PrimaryKeyJoinColumn(name = "media_id")
public class MediaWeixin extends Media {

	private String weixinCode;

	@Column(name = "WEIXIN_CODE", nullable = false, length = 60)
	public String getWeixinCode() {
		return this.weixinCode;
	}

	public void setWeixinCode(String weixinCode) {
		this.weixinCode = weixinCode;
	}

}
