package com.lczy.media.entity;

// Generated 2015-6-30 13:49:25 by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.hibernate.annotations.GenericGenerator;

/**
 * MediaQuote generated by hbm2java
 */
@Entity
@Table(name = "t_media_quote_log")
public class MediaQuoteLog {
	
	private String id;
	private Media media;
	private String type;
	private Integer price;
	private Integer priceMedia;
	private Integer tax;
	private String createBy;
	private Date createTime;
	private String auditBy;
	private Date auditTime;
	private String modifyType;
	private String status;
	private boolean provideInvoice;

	public MediaQuoteLog() {
	}

	public MediaQuoteLog(String id, Media media, String type, Integer price, Integer priceMedia,
			int tax, Date createTime, Date modifyTime, String modifyType) {
		this.id = id;
		this.media = media;
		this.type = type;
		this.price = price;
		this.tax = tax;
		this.priceMedia = priceMedia;
		this.createTime = createTime;
		this.modifyType = modifyType;
	}

	public MediaQuoteLog(String id, Media media, String type, Integer price, Integer priceMedia, Integer tax,
			String createBy, Date createTime, String modifyBy, Date modifyTime, String modifyType) {
		this.id = id;
		this.media = media;
		this.type = type;
		this.price = price;
		this.tax = tax;
		this.priceMedia = priceMedia;
		this.createBy = createBy;
		this.createTime = createTime;
		this.modifyType = modifyType;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@GeneratedValue(generator = "system-uuid")
	@GenericGenerator(name = "system-uuid", strategy = "uuid")
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MEDIA_ID", nullable = false)
	public Media getMedia() {
		return this.media;
	}

	public void setMedia(Media media) {
		this.media = media;
	}

	@Column(name = "TYPE", nullable = false, length = 32)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "PRICE", nullable = false)
	public Integer getPrice() {
		return this.price;
	}

	public void setPrice(Integer price) {
		this.price = price;
	}
	
	@Column(name = "PRICE_MEDIA", nullable = false)
	public Integer getPriceMedia() {
		return priceMedia;
	}

	public void setPriceMedia(Integer priceMedia) {
		this.priceMedia = priceMedia;
	}
	@Column(name = "TAX")
	public Integer getTax() {
		return tax;
	}

	public void setTax(Integer tax) {
		this.tax = tax;
	}

	@Column(name = "CREATE_BY", length = 32)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", nullable = false, length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
	
	
	@Column(name = "AUDIT_BY", length = 32)
	public String getAuditBy() {
		return auditBy;
	}

	public void setAuditBy(String auditBy) {
		this.auditBy = auditBy;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "AUDIT_TIME", nullable = false, length = 19)
	public Date getAuditTime() {
		return auditTime;
	}

	public void setAuditTime(Date auditTime) {
		this.auditTime = auditTime;
	}

	@Column(name = "MODIFY_TYPE", length = 32)
	public String getModifyType() {
		return modifyType;
	}

	public void setModifyType(String modifyType) {
		this.modifyType = modifyType;
	}
	
	@Column(name = "STATUS", length = 32)
	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}
	
	
	@Column(name = "PROVIDE_INVOICE")
	public boolean isProvideInvoice() {
		return provideInvoice;
	}

	public void setProvideInvoice(boolean provideInvoice) {
		this.provideInvoice = provideInvoice;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}
		if (obj == this) {
			return true;
		}
		if (obj.getClass() != getClass()) {
			return false;
		}
		
		MediaQuoteLog that = (MediaQuoteLog) obj;
		return new EqualsBuilder().append(id, that.getId())
				.append(type, that.getType())
				.append(price, that.getPrice())
				.isEquals();
	}
	
}
