package com.lczy.media.entity;

// Generated 2015-3-31 12:34:17 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * MediaWeibo generated by hbm2java
 */
@Entity
@Table(name = "t_media_weibo")
@PrimaryKeyJoinColumn(name = "media_id")
public class MediaWeibo extends Media {

	private String weiboPlatform;

	@Column(name = "WEIBO_PLATFORM", length = 32)
	public String getWeiboPlatform() {
		return this.weiboPlatform;
	}

	public void setWeiboPlatform(String weiboPlatform) {
		this.weiboPlatform = weiboPlatform;
	}

}
