package com.lczy.media.entity;

// Generated 2015-4-3 16:57:30 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * MediaAdv generated by hbm2java
 */
@Entity
@Table(name = "t_media_adv")
public class MediaAdv implements java.io.Serializable {

	private String id;
	private String type;
	private Media media;
	private String img;
	private int orders;

	public MediaAdv() {
	}

	public MediaAdv(int orders) {
		this.orders = orders;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@GeneratedValue(generator = "system-uuid")
	@GenericGenerator(name = "system-uuid", strategy = "uuid")
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "type", length = 30)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "media_id")
	public Media getMedia() {
		return media;
	}

	public void setMedia(Media media) {
		this.media = media;
	}

	@Column(name = "orders", nullable = false)
	public int getOrders() {
		return this.orders;
	}

	public void setOrders(int orders) {
		this.orders = orders;
	}

	public String getImg() {
		return img;
	}

	public void setImg(String img) {
		this.img = img;
	}
	
	
}
