package com.lczy.media.entity;

// Generated 2015-3-27 17:06:05 by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Cacheable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * MediaTagMergeLog generated by hbm2java
 */
@Entity
@Table(name = "t_media_tag_merge_log")
@Inheritance(strategy = InheritanceType.JOINED)
@Cacheable
public class MediaTagMergeLog {

	private String id;
	private String masterName;
	private Integer masterCount;
	private String slaveName;
	private Integer slaveCount;
	private String createBy;
	private Date createTime;

	public MediaTagMergeLog() {
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@GeneratedValue(generator = "system-uuid")
	@GenericGenerator(name = "system-uuid", strategy = "uuid")
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "MASTER_NAME", nullable = false, length = 64)
	public String getMasterName() {
		return this.masterName;
	}

	public void setMasterName(String masterName) {
		this.masterName = masterName;
	}

	@Column(name = "MASTER_COUNT")
	public Integer getMasterCount() {
		return this.masterCount;
	}	

	public void setMasterCount(Integer masterCount) {
		this.masterCount = masterCount;
	}	

	@Column(name = "SLAVE_NAME", nullable = false, length = 64)
	public String getSlaveName() {
		return this.slaveName;
	}

	public void setSlaveName(String slaveName) {
		this.slaveName = slaveName;
	}

	@Column(name = "SLAVE_COUNT")
	public Integer getSlaveCount() {
		return this.slaveCount;
	}	

	public void setSlaveCount(Integer slaveCount) {
		this.slaveCount = slaveCount;
	}	

	@Column(name = "CREATE_BY", length = 32)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", nullable = false, length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

}
