package com.lczy.media.entity;

// Generated 2015-3-27 18:53:05 by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * OpLogging generated by hbm2java
 */
@Entity
@Table(name = "c_op_logging")
public class OpLogging implements java.io.Serializable {

	private static final long serialVersionUID = -6554907300558549953L;
	private String id;
	private String actionType;
	private String description;
	private String oldVal;
	private String newVal;
	private String userId;
	private Date createTime;
	private String ip;
	private String memo;

	public OpLogging() {
	}

	public OpLogging(String id) {
		this.id = id;
	}

	public OpLogging(String id, String actionType, String description,
			String oldVal, String newVal, String userId, Date createTime,
			String ip, String memo) {
		this.id = id;
		this.actionType = actionType;
		this.description = description;
		this.oldVal = oldVal;
		this.newVal = newVal;
		this.userId = userId;
		this.createTime = createTime;
		this.ip = ip;
		this.memo = memo;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@GeneratedValue(generator = "system-uuid")
	@GenericGenerator(name = "system-uuid", strategy = "uuid")
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "ACTION_TYPE", length = 20)
	public String getActionType() {
		return this.actionType;
	}

	public void setActionType(String actionType) {
		this.actionType = actionType;
	}

	@Column(name = "DESCRIPTION", length = 128)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "OLD_VAL", length = 4000)
	public String getOldVal() {
		return this.oldVal;
	}

	public void setOldVal(String oldVal) {
		this.oldVal = oldVal;
	}

	@Column(name = "NEW_VAL", length = 4000)
	public String getNewVal() {
		return this.newVal;
	}

	public void setNewVal(String newVal) {
		this.newVal = newVal;
	}

	@Column(name = "USER_ID", length = 32)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "IP", length = 128)
	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	@Column(name = "MEMO", length = 500)
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

}
